language: go

sudo: required
services:
  - docker

go:
 - 1.3
 - 1.4
 - 1.5
 - 1.6
 - tip

go_import_path: github.com/osrg/gobgp

env:
 - SCENARIO=false
 - SCENARIO=true

matrix:
  exclude:
    - go: 1.3
      env: SCENARIO=true
    - go: 1.4
      env: SCENARIO=true
    - go: 1.5
      env: SCENARIO=true
    - go: tip
      env: SCENARIO=true

script:
 - bash test/scenario_test/ci-scripts/travis-build-script.sh $SCENARIO

notifications:
 slack:
  secure: KzuC9kytzS7wTlfj4MqSg8EpqXfJRMbo59dAVTA3w587achnVCS3vhUenWuhMCiWk7+6DVWwNpwzn2+A0S6RwMFMpKAU6Ij6K9sxEOgqBGuMN8w1//w+uJTryzsnebEIhInGt2kKfqz4Wx3QQqW5gVhI+8s+c5M0iXxFtN4soVk=
